# Generated by Django 4.2.28 on 2026-02-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-pickup_time']},
        ),
        migrations.AlterModelOptions(
            name='rideevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id_user']},
        ),
    ]
